feat: allow custom headers to be sent through http requests
gouline/dbt-metabase pull request #180
Opened 2023-10-04 08:33 UTC by tanguyantoine

# What 

- add new options to CLI: extra_http_headers

# Why

- it allows to provide extra headers to requests sent to Metabase instance

# Use case

it allows instances to be reached when they are deployed behind security system (ex https://developers.cloudflare.com/cloudflare-one/identity/service-tokens/#connect-your-service-to-access)

example

```bash
dbt-metabase models --http_extra_headers CF-Access-Client-Id $CF_CLIENT_ID --http_extra_headers CF-Access-Client-Secret $CF_CLIENT_SECRET
```

2023-10-04 21:51 UTC, tanguyantoine commented
@gouline I have run black to format the files correctly

2023-10-04 23:19 UTC, gouline commented
To save time, run all the checks locally prior to pushing commits.

2023-10-05 10:50 UTC, tanguyantoine commented
@gouline sorry for that, I have run make check and it is working now :-)

2023-10-05 23:10 UTC, gouline requested changes

2023-10-05 23:10 UTC, gouline commented on dbtmetabase/__init__.py
> +    no CLI flag is passed, but a value is provided in the config file (e.g. metabase_use_http: True).
Revert all changes unrelated to the functionality you're implementing (e.g. removing newlines, moving comment quotes)

2023-10-06 00:41 UTC, gouline commented on dbtmetabase/__init__.py
> +    no CLI flag is passed, but a value is provided in the config file (e.g. metabase_use_http: True).
Sorry, I discovered this was misalignment in formatter versions, which I have now fixed in the master.

2023-10-06 00:44 UTC, gouline approved these changes

2023-10-06 00:44 UTC, merged