In case of missing resource {dashboard, card, user}, dbt-metabase ski…
gouline/dbt-metabase pull request #238
Opened 2024-02-28 15:04 UTC by dosnep

Closing #237

2024-02-28 23:03 UTC, gouline requested changes
Please read [CONTRIBUTING.md](https://github.com/gouline/dbt-metabase/blob/master/CONTRIBUTING.md#pull-requests) for local checks to run before committing, to avoid waiting for failed CI.

2024-02-28 23:03 UTC, gouline commented on dbtmetabase/metabase.py
>      def get_card(self, uid: str) -> Mapping:
```suggestion
    def find_card(self, uid: str) -> Optional[Mapping]:
```

2024-02-28 23:03 UTC, gouline commented on dbtmetabase/metabase.py
>      def get_dashboard(self, uid: str) -> Mapping:
```suggestion
    def find_dashboard(self, uid: str) -> Optional[Mapping]:
```

2024-03-04 16:50 UTC, dosnep commented
> ommitting, to avoid waiting for failed CI.

CI has been tested locally (fmt-check and unit tests)

2024-03-04 23:03 UTC, gouline commented
Please read [CONTRIBUTING.md](https://github.com/gouline/dbt-metabase/blob/master/CONTRIBUTING.md#pull-requests) **carefully**. You only ran the formatting check, you have to run all of them.

2024-03-04 23:13 UTC, merged