feat: Add flag to skip syncing sources, and allow meta-defined display names
gouline/dbt-metabase pull request #95
Opened 2022-04-12 15:39 UTC by atvaccaro

This tool is amazing!

I have a couple features that may be helpful.

First, adding a flag to skip all dbt sources. In [our project](https://github.com/cal-itp/data-infra/tree/main/warehouse), we ultimately use Metabase on top of BigQuery, but we don't import source datasets into Metabase. Without the flag, `dbt-metabase` throws errors as it tries to sync dbt source models.

Second, adding `metabase.display_name` as an optional field. We deal with a lot of [GTFS](https://gtfs.org/) data, so our model names naturally have GTFS as a common acronym. Currently it gets title-cased as `Gtfs` in many situations, which is annoying. So I wanted to have the ability to override the Metabase `display_name` property.

2022-04-13 03:56 UTC, gouline requested changes
Run CI checks locally and fix any failures _before_ pushing, GitHub waits for me to run them in Actions for first-time contributors.

@z3z1ma Do you remember what source models are used for after reading, apart from being exported to Metabase? If they are not exported, is there any point in reading them in the first place? Trying to think whether they should be excluded from the Metabase client (how this PR implements it) or from being read in the parsers.

2022-04-13 03:56 UTC, gouline commented on dbtmetabase/logger/logging.py
> +import os
Redundant.

2022-04-13 03:56 UTC, gouline commented on dbtmetabase/__init__.py
> +    metabase_sync_sources: bool = False,
"Sync" only relates to polling for changes, not for the action of _exporting_ the models. Your change also changes the default behaviour, which will break the build for anyone expecting the sources to be exported.

The flag should be something along the lines of `exclude_sources` default to false and only NOT export sources when it's set to true.

2022-04-13 20:53 UTC, atvaccaro commented
> Run CI checks locally and fix any failures _before_ pushing, GitHub waits for me to run them in Actions for first-time contributors.

Ah I'm sorry! To be honest I didn't notice them until I got the failure email, but will do that.

Re: formatting, I don't see a `black` version pinned. Would you be open to pinning 22.3.0?

2022-04-13 21:08 UTC, z3z1ma commented
@atvaccaro 

black is in `requirements-test.txt` but it isn't pinned. No deps are pinned currently actually, though the latest compatible versions would be chosen on fresh install.

@gouline 
`dbt-metabase models`  only uses source for exporting definitions.
`dbt-metabase exposures` uses sources as possible matches for BI exposure extraction

I think it might be cleaner/more logical to exclude in the parser with a flag and only pass that flag from the `models` command when the CLI flag `exclude_sources` is passed

2022-04-13 23:59 UTC, gouline commented
> Re: formatting, I don't see a `black` version pinned. Would you be open to pinning 22.3.0?

No regular work is done on this repository so nobody will be updating those pinned versions, use latest. Create a virtual env if it conflicts with other projects.

2022-07-05 04:40 UTC, gouline commented
@atvaccaro Still planning to get this merged?

2022-07-06 10:14 UTC, merged

2022-09-19 18:32 UTC, atvaccaro commented
> @atvaccaro Still planning to get this merged?

Hey I'm so sorry and thank you for getting this through. I've been heads-down on a major project and refactor and never got back to this.